<?php
session_start();
//print_r($_SESSION['user']);
?>
<!doctype html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
  <meta name="generator" content="Hugo 0.88.1">
  <title>Homepage</title>

  <link rel="canonical" href="https://getbootstrap.com/docs/5.1/examples/dashboard/">



  <!-- Bootstrap core CSS -->
  <link href="../node_modules/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" crossorigin="anonymous">


  <style>
    body {
      padding: 2rem 0rem;
    }

    .card-img {
      border-bottom-left-radius: 0px;
      border-bottom-right-radius: 0px;
    }

    .card-title {
      margin-bottom: 0.3rem;
    }

    .cat {
      display: inline-block;
      margin-bottom: 1rem;
    }

    .fa-users {
      margin-left: 1rem;
    }

    .card-footer {
      font-size: 0.8rem;
    }

    body {
      font-family: Helvetica;
      margin: 0;
      padding-top: 0px;
    }

    a {
      text-decoration: none;
      color: #ccc;
    }

    .site-header {
      border-bottom: 1px solid #ccc;
      padding: .5em 1em;
      display: flex;
      justify-content: space-between;
      background-color:#000;
      margin-bottom: 25px;
    }

    .site-identity h1 {
      font-size: 2.0em;
      margin: .6em 0;
      display: inline-block;
      color: #ccc;
    }


    .site-navigation ul,
    .site-navigation li {
      margin: 0;
      padding: 0;
      color: #ccc;
    }

    .site-navigation li {
      display: inline-block;
      margin: 1.4em 1em 1em 1em;
      color: #ccc;
    }
  </style>


  <!-- Custom styles for this template -->
  <!-- <link href="./assets/css/dashboard.css" rel="stylesheet"> -->
</head>

<body>


  <header class="site-header">
    <div class="site-identity">
      <h1><a href="<?php echo URLROOT;?>blog/home">Blog it</a></h1>
    </div>
    <nav class="site-navigation">
      <ul class="nav">
        <?php
        if (isset($_SESSION['user'])) {
            if ($_SESSION['user']['role']=='admin') {
                echo '<li><a href="'.URLROOT.'dashboard/index/users">Dashboard</a></li>';
            }
        }
        ?>
        <li><a href="<?php echo URLROOT;?>blog/write">Write your own blog</a></li>
        <?php
        if (isset($_SESSION['user'])) {
            echo '<li><a href="'.URLROOT.'login">Sign out</a></li>';
        } else {
            echo '<li><a href="'.URLROOT.'login">Sign in</a></li>';
        }
        ?>
        
      
      </ul>
    </nav>
  </header>


  <div class="container">
    <div class="row">
  
    <?php
    foreach ($blogs as $val) {
            echo ' <div class="col-12 col-sm-8 col-md-6 col-lg-4">
            <div class="card">
              <img class="card-img" 
              src="https://s3.eu-central-1.amazonaws.com/bootstrapbaymisc/blog/24_days_bootstrap/pasta.jpg" 
              alt="Bologna">
              <div class="">
                <a href="" class="btn btn-light btn-sm">'.$val->category.'</a>
              </div>
              <div class="card-body">
                <h4 class="card-title">'.$val->heading.'</h4>
                <small class="text-muted cat">
    
                </small>
                <p class="card-text">'.$val->brief.'</p>
                <a href="'.URLROOT.'blog/read/'.$val->id.'" class="btn btn-info">Read Blog</a>
              </div>
              <div class="card-footer text-muted d-flex justify-content-between bg-transparent border-top-0">
                <div class="views">'.substr($val->date, 0, 22).'
                </div>
    
              </div>
            </div>
          </div>';
    }
        ?>

    </div>
  </div>
</body>

</html>