<?php
// var_dump($blog['read']->id);
?>
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="<?php echo URLROOT;?>/node_modules//bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />
    </head>
    <body>
        <header>
            <div class="collapse bg-dark" id="navbarHeader">
              <div class="container">
                <div class="row">
                 
                </div>
              </div>
            </div>
            <div class="py-3 navbar navbar-dark bg-dark shadow-sm">
              <div class="container">
                <a href="<?php echo URLROOT;?>blog/home" class="navbar-brand d-flex align-items-center">
                  <strong class="fs-4">Blog it</strong>
                </a>
                
              </div>
            </div>
          </header>
        <!-- Product section-->
        <section class="py-5">
            <div class="container px-4 px-lg-5 my-5">
                <div class="row gx-4 gx-lg-5 align-items-center">
                    <div class="col-md-12"><img class="card-img-top mb-5 mb-md-0" 
                    src="https://s3.eu-central-1.amazonaws.com/bootstrapbaymisc/blog/24_days_bootstrap/pasta.jpg" style="height: 350px;"></div>
                    <div class="col-md-10">
                       
                        <h1 class="display-5 fw-bolder"><?php echo $blog['read']->heading ?></h1>
                        <div class="small mb-1">published:<?php echo " ".$blog['read']->date ;?> </div>
                        <div class="fs-5 mb-5">
                            <span>by:<?php echo " ".$blog['read']->username ;?> </span>
                        </div>
                       
                      
                        <p class="lead">
                        <?php echo " ".$blog['read']->content; ?></p>
                       
                    </div>
                </div>
            </div>
        </section>
     
        <!-- Footer-->
        <footer class="py-5 bg-dark">
            <div class="container"><p class="m-0 text-center text-white">&copy; Blog it</p></div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="../node_modules/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="js/scripts.js"></script>
    </body>
</html>