
    <!-- Bootstrap core CSS -->
    <link href="<?php echo URLROOT;?>node_modules/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" crossorigin="anonymous">


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }
      .errors{
      color: red;
      font-size: large;
    }

    .success{
      color: green;
      font-size: large;
    }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>

    
    <!-- Custom styles for this template -->
    <link href="<?php echo URLROOT;?>assets/css/dashboard.css" rel="stylesheet">
  </head>
  <body>
    
<header class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow">
  <a class="navbar-brand col-md-3 col-lg-2 me-0 px-3" href="<?php echo URLROOT;?>blog/home">Blog it</a>
  <button class="navbar-toggler position-absolute d-md-none collapsed" 
  type="button" data-bs-toggle="collapse" data-bs-target="#sidebarMenu" 
  aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <!-- <input class="form-control form-control-dark w-100" type="text" placeholder="Search" aria-label="Search"> -->
  <div class="navbar-nav">
    <div class="nav-item text-nowrap">
      <a class="nav-link px-3" href="<?php echo URLROOT; ?>login">Sign out</a>
    </div>
  </div>
</header>

<div class="container-fluid">
  <div class="row">
    <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
      <div class="position-sticky pt-3">
        <ul class="nav flex-column">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="<?php echo URLROOT;?>blog/home">
              <span data-feather="home"></span>
              Home
            </a>
          </li>
         
        </ul>
      </div>
    </nav>

    <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
      <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 
       pb-2 mb-3 border-bottom">
        <h1 class="h2">Write Blog</h1>

      </div>
      <?php if(isset($message)) { ?>
      <div class="alert alert-<?php echo $success === true ? 'success' : 'danger'; ?>">
    <?php echo $message; ?>
</div>
<?php }?>
        
      <form class="row g-3" action="" method="POST" enctype="multipart/form-data">
        <div class="col-md-6">
          <label for="name" class="form-label">Heading</label>
          <input type="text" class="form-control" id="heading" name="heading">
        </div>
          <div class="col-md-2">
          <label for="category" class="form-label">Category</label>
          <select id="category" class="form-select" name="category">
           <option>General</option>
            <option>Electronics</option>
            <option>Fashion</option>
            <option>Furniture</option>
            <option>Cooking</option>
            <option>Mobiles</option>
            
          </select>
        </div>

        <div class="col-md-4">
          <label for="tags" class="form-label">Tags</label>
          <input type="text" class="form-control" id="tags" name="tags">
        </div>
        <div class="col-md-6">
          <label for="tags" class="form-label">Brief description</label>
          <input type="text" class="form-control" id="tags" name="brief">
        </div>
        <div class="col-12">
          <label for="content" class="form-label">Your Blog</label>
          <textarea class="form-control" id="content" name="content" style="height: 280px;">
          </textarea>
        </div>
       
        <div class="col-12">
          <div class="form-check">
            <input class="form-check-input" type="checkbox" id="gridCheck" required>
            <label class="form-check-label" for="gridCheck">
              Confirm
            </label>
          </div>
        </div>
        <div class="col-12">
          <button type="submit" class="btn btn-primary" name="submit" value="writeBlog">Publish</button>
        </div>
      </form>      
    </main>
  </div>
</div>


    <script src="../node_modules/bootstrap/dist/js/bootstrap.bundle.js" 
    integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" 
    crossorigin="anonymous"></script>
  </body>